replicaCount: 1
image:
  repository: barakvalzer/flask-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  host: ""
  annotations: {}
  tls: []
env: []
